#!/bin/bash

# Launch pd and connect it to Teensy midi device for output and a generic usb interface for input
# Based on a script at tedfelix.com/linux/linux-midi.html
# And parts from guitarextended.wordpress.com/2012/08/28/running-pd-on-a-headless-raspberry-pi/


echo "Starting Pd..."
pd -nogui -verbose -stderr -alsa -audioadddev pisound -alsamidi -channels 2 -r 44100 -midiindev 2 -midioutdev 2 /home/pi/line_of_karman/pd/main.pd &

sleep 5

#use aconnect to get the ports
pdin=$(aconnect -i | grep "Pure Data" | cut -d ' ' -f 2)0
pdout=$(aconnect -o | grep "Pure Data" | cut -d ' ' -f 2)1
sensorin=$(aconnect -i | grep "LASER" | cut -d ' ' -f 2)0
teensyout=$(aconnect -i | grep "Teensy" | cut -d ' ' -f 2)0

echo pdin: $pdin
echo pdout: $pdout
echo sensorin: $sensorin
echo teensyout: $teensyout

aconnect $pdout $teensyout
aconnect $sensorin $pdin
